env:
  global:
    - VERSION=1.${TRAVIS_BUILD_NUMBER}
    - DOCKER_HUB_USER=vfarcic

sudo: required

services:
  - docker

before_install:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then openssl aes-256-cbc -K $encrypted_9acc217090f3_key -iv $encrypted_9acc217090f3_iv -in proxy-key.enc -out proxy-key -d; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then chmod 600 proxy-key; fi'

script:
  - docker build -t vfarcic/docker-flow-swarm-listener .
  - docker tag vfarcic/docker-flow-swarm-listener vfarcic/docker-flow-swarm-listener:beta
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker push vfarcic/docker-flow-swarm-listener:beta
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then docker tag vfarcic/docker-flow-swarm-listener vfarcic/docker-flow-swarm-listener:${VERSION}; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then docker push vfarcic/docker-flow-swarm-listener:${VERSION}; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then docker push vfarcic/docker-flow-swarm-listener; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then docker-compose run --rm docs; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then docker build -t vfarcic/docker-flow-swarm-listener-docs -f Dockerfile.docs .; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then docker tag vfarcic/docker-flow-swarm-listener-docs vfarcic/docker-flow-swarm-listener-docs:${VERSION}; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then docker push vfarcic/docker-flow-swarm-listener-docs:${VERSION}; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then docker push vfarcic/docker-flow-swarm-listener-docs; fi'

branches:
  only:
    - master
